### ISSUE TITLE
There is a memory leak in "indexedJobsByName" map which holds the submitted jobs in the scheduler.

### ISSUE THREAD

**Issue by ashfaque15492** [Coreoz/Wisp#21]
There is a memory leak in "indexedJobsByName" map which holds the submitted jobs in the scheduler, it holds the jobs instance and causes a out of memory based on heap size configurations and #of jobs submitted to the scheduler. 

This issue should be fixed as those who initializes the scheduler once and submits the job with lambda directly, the map entries does not get cleared. 
![IMG_7848](https://github.com/Coreoz/Wisp/assets/11074114/19d3ede2-d2fc-4848-b179-dd08d096f544)

**Comment by amanteaux** [comment]
Thank you for your report.

In our general use case this is not an issue because we create a small number of tasks. Also, to manually force a job to be run, the current recommended workflow is to cancel the job, and then reschedule it with a first start time set as `now`.

Can you confirm that your use case is different: you dynamically create many tasks that have a short life span... And then you notice the memory leak you reported. Is this correct?

I can see two approaches to solve this problem:
1. Add a `scheduler.cleanUpTerminatedJobs()` method that you would call manually from time to time
2. Add a configuration value to enable automatic cleaning. But if enabled, it would mean:
   1. You would not be able to get stats for terminated jobs
   2. You would not be able to manually force an active job to start
   3. You would not be able to restart a terminated job

What do you think about this?

**Comment by ashfaque15492** [comment]
Yes we are submitting different jobs at user defined intervals, it could have hundreds of jobs scheduled over a period of time and scheduled does not get terminated once started, also submitted jobs does not have any names that so lambda object reference gets stored as key to "indexedJobsByName" map. 

Regarding your suggestion, I could not see scheduler.cleanUpTerminatedJobs(), could you please share a reference so that we can try this.

**Comment by amanteaux** [comment]
Sorry if I wasn't clear: currently there is no option that enables you to release the memory taken by Wisp.

I was proposing you two new developments inside Wisp to address this issue.

Do you have any preference?

**Comment by amanteaux** [comment]
Actually I gave it some thoughts, I will provide:
- A method to remove a job from a the scheduler (that will cancel the job if it is still running)
- A job like `LongRunningJobMonitor` to do some cleanup of "old" terminated jobs

**Comment by ashfaque15492** [comment]
Yeah either of them are good to have, we can be unblocked by either of those, thanks for prompt response

**Comment by ashfaque15492** [comment]
@amanteaux any update on above issue, we are blocked in production

**Comment by amanteaux** [comment]
A fix should be available by the end of this week.

Although, note that this is an open source library without any paid support. So if you are really in a rush, you can use Java reflection to solve quickly your issue ;)

**Comment by ashfaque15492** [comment]
ok, thanks

**Comment by amanteaux** [comment]
Fixed in release 2.4.0. See https://github.com/Coreoz/Wisp#cleanup-old-terminated-jobs
