### ISSUE TITLE
Forcing executing a job

### ISSUE THREAD

**Issue by mbigatti** [Coreoz/Wisp#5]
I'm using Wisp to schedule a bunch of processes, using Cron expressions. I would like to be able to force run a job before its due date. I see this is possible running directly the `Runnable` from a `Job` instance, but in this way the run count and latest run timestamp are not updated. From what I see from the source code I can't update externally those values; is there any workaround? It is something that you would like to add to the project? I could provide a pull request if so.

**Comment by amanteaux** [comment]
Actually I think that running a job immediately is not really a logic that should be implemented in Wisp because it can actually vary between different use cases. For example we are currently implementing in our administration area a way of executing immediately a job, but we do not want to execute the job if it will be executed in less that 5 seconds. Here is the code if you are interested: https://github.com/Coreoz/Plume-admin/pull/2/files#diff-6b331bc4e8b9be8375ccc42ca38abaceR52 
If you want to reuse this code, you will need to use the 2.1.0-SNAPSHOT version of Wisp (which should be released in a week or two).

At last, if you really want to have control over the statistics, you can build a proxy on top of Wisp so your UI/logic will use the values returned by your proxy. And you will be able to manually changes your proxy values.

**Comment by mbigatti** [comment]
Thank you for the info and insights. I'll check the repo in a few weeks for the updated version and I'll definitively build a statistics proxy.

**Comment by amanteaux** [comment]
@mbigatti Version 2.1.0 has been released: https://github.com/Coreoz/Wisp/releases/tag/2.1.0
